name: Rankup
version: 3.1.2
main: sh.okx.rankup.Rankup
author: Okx
depend: [Vault]
softdepend: [PlaceholderAPI]
api-version: 1.13

commands:
    rankup:
        permission: rankup.rankup
        description: Rankup.
    rankup3:
        permission: rankup3.info
        description: View Rankup version and perform some administrative commands.
        # support the old command
        aliases: [pru]
    ranks:
        permission: rankup.ranks
        description: List all the ranks.
    prestige:
        permission: rankup.prestige
        description: Prestige.
    prestiges:
        permission: rankup.prestiges
        description: List all the prestiges.
permissions:
    rankup.*:
        children:
            rankup.info: true
            rankup.rankup: true
            rankup.checkversion: true
            rankup.ranks: true
            rankup.reload: true
            rankup.prestige: true
            rankup.prestiges: true
    rankup.info:
        default: true
    rankup.rankup:
        default: true
    rankup.checkversion:
        default: op
    rankup.reload:
        default: op
    rankup.ranks:
        default: true
    rankup.prestige:
        default: true
    rankup.prestiges:
        default: true