name: Rankup
version: ${version}
main: sh.okx.rankup.Rankup
author: Okx
depend: [Vault]
softdepend: [PlaceholderAPI, mcMMO, AdvancedAchievements, Towny]
api-version: 1.13

commands:
  rankup:
    permission: rankup.rankup
    description: Rankup.
  rankup3:
    permission: rankup3.info
    description: View Rankup version and perform some administrative commands.
    # support the old command
    aliases: [pru]
  ranks:
    permission: rankup.ranks
    description: List all the ranks.
  prestige:
    permission: rankup.prestige
    description: Prestige.
  prestiges:
    permission: rankup.prestiges
    description: List all the prestiges.
permissions:
  rankup.*:
    children:
      rankup.info: true
      rankup.rankup: true
      rankup.admin: true
      rankup.ranks: true
      rankup.prestige: true
      rankup.prestiges: true
      rankup.auto: true
  rankup.admin:
    children:
      # if a player can see if the plugin needs updating when they run /pru
      rankup.checkversion: true
      # if a player can run /pru reload
      rankup.reload: true
      # if a player can force rankup or prestige someone
      rankup.force: true
      # if a player receives notifications to update rankup when the log in.
      rankup.notify: true
    default: op
  rankup.info:
    default: true
  rankup.rankup:
    default: true
  rankup.ranks:
    default: true
  rankup.prestige:
    default: true
  rankup.prestiges:
    default: true
  rankup.auto:
    default: true